import type { LessonDetail } from "@/lib/types"

// Core Korean extension for Hengo Foundations.
//
// These lessons intentionally sit at the end of the existing grammar track.
// They fill practical beginner gaps that matter for living and working in Korea:
// understanding Korean word classes, asking questions, handling numbers/time,
// and choosing respectful workplace language. Content is authored and stable;
// learner progress remains in Supabase (kori_foundation_progress).
export const CORE_KOREAN_FOUNDATIONS_VERSION = "2026-09-03.1"

export const CORE_KOREAN_FOUNDATIONS: LessonDetail[] = [
  {
    id: "grammar-19",
    track: "grammar",
    order: 19,
    title: "Korean Words & Parts of Speech",
    subtitle: "Know what kind of word you are looking at",
    level: "Beginner",
    estimatedMinutes: 12,
    completed: false,
    progress: 0,
    intro:
      "You do not need to memorize linguistic terminology to speak Korean, but recognizing the main word types makes dictionaries, grammar explanations, and sentence building much easier. Korean verbs and descriptive verbs normally appear in dictionaries with -다; particles attach to nouns; and endings attach to verb/adjective stems.",
    cards: [
      {
        hangul: "명사 — noun",
        romanization: "myeongsa",
        meaning: "A person, place, thing, or idea.",
        example: "회사 · 회의 · 개발자 · 일정",
        exampleTranslation: "company · meeting · developer · schedule",
      },
      {
        hangul: "대명사 — pronoun",
        romanization: "daemyeongsa",
        meaning: "A word that stands in for a noun.",
        example: "저 · 나 · 이것 · 누구",
        exampleTranslation: "I (polite) · I (casual) · this thing · who",
        note: "In natural Korean, pronouns are often omitted when the context is already clear.",
      },
      {
        hangul: "동사 — verb",
        romanization: "dongsa",
        meaning: "An action or process. Dictionary forms usually end in -다.",
        example: "가다 → 가요 · 확인하다 → 확인해요",
        exampleTranslation: "to go → go · to check → check",
        note: "Remove -다 to see the stem: 가다 → 가-, 먹다 → 먹-, 확인하다 → 확인하-.",
      },
      {
        hangul: "형용사 — descriptive verb",
        romanization: "hyeongyongsa",
        meaning:
          "Words such as 좋다, 어렵다, and 바쁘다 describe a state but conjugate like verbs in Korean.",
        example: "오늘 조금 바빠요.",
        exampleTranslation: "I am a little busy today.",
      },
      {
        hangul: "부사 — adverb",
        romanization: "busa",
        meaning: "Describes how, when, or to what degree something happens.",
        example: "지금 · 다시 · 빨리 · 천천히 · 조금",
        exampleTranslation: "now · again · quickly · slowly · a little",
      },
      {
        hangul: "관형사 — determiner",
        romanization: "gwanhyeongsa",
        meaning: "Comes directly before a noun to point out or describe which one.",
        example: "이 방법 · 그 문제 · 저 사람 · 어떤 작업 · 무슨 일",
        exampleTranslation: "this method · that problem · that person · which task · what kind of work",
      },
      {
        hangul: "수사 — numeral",
        romanization: "susa",
        meaning: "Number words. Korean uses both native Korean and Sino-Korean number systems.",
        example: "하나, 둘, 셋 / 일, 이, 삼",
        exampleTranslation: "one, two, three / one, two, three",
      },
      {
        hangul: "조사 — particle",
        romanization: "josa",
        meaning: "Small markers attached to nouns that show their role or relationship.",
        example: "은/는 · 이/가 · 을/를 · 에 · 에서 · 도 · 만",
        exampleTranslation: "topic · subject · object · location/time · action location · also · only",
      },
      {
        hangul: "감탄사 — interjection",
        romanization: "gamtansa",
        meaning: "Short independent reactions or responses.",
        example: "네 · 아니요 · 아 · 어",
        exampleTranslation: "yes · no · ah · uh",
      },
      {
        hangul: "어미 — endings",
        romanization: "eomi",
        meaning:
          "Not a basic part-of-speech category like the items above, but essential for learners: endings attach to stems and carry tense, politeness, connection, intention, and more.",
        example: "가요 · 갑니다 · 가고 · 가면",
        exampleTranslation: "go (polite) · go (formal) · and go · if/when (someone) goes",
      },
    ],
    exercises: [
      {
        id: "grammar-19-e1",
        type: "multiple-choice",
        prompt: "Which item is a 조사 (particle)?",
        options: ["회의", "빨리", "은/는", "가다"],
        answerIndex: 2,
        explanation: "은/는 is a topic particle attached to a noun.",
      },
      {
        id: "grammar-19-e2",
        type: "multiple-choice",
        prompt: "What is the dictionary form of 가요?",
        options: ["가", "가다", "가요다", "갑니다"],
        answerIndex: 1,
        explanation: "Korean dictionary verb forms normally end in -다 → 가다.",
      },
      {
        id: "grammar-19-e3",
        type: "type-answer",
        prompt: "Type the Korean term for 'verb'.",
        answer: "동사",
        explanation: "동사 means verb.",
      },
    ],
  },
  {
    id: "grammar-20",
    track: "grammar",
    order: 20,
    title: "Questions & Demonstratives",
    subtitle: "Who, what, where, when, why, how — and this/that",
    level: "Beginner",
    estimatedMinutes: 11,
    completed: false,
    progress: 0,
    intro:
      "A small set of question words unlocks a huge amount of daily Korean. Korean question words usually stay in the same position where the answer would appear. Pair them with 이/그/저 and 여기/거기/저기 so you can ask about people, places, things, schedules, and tasks.",
    cards: [
      {
        hangul: "누구 / 뭐(무엇) / 어디",
        romanization: "nugu / mwo(mueot) / eodi",
        meaning: "who / what / where",
        example: "이 작업은 누가 담당하나요?",
        exampleTranslation: "Who is responsible for this task?",
        note: "누구 + 가 commonly contracts to 누가.",
      },
      {
        hangul: "언제 / 왜 / 어떻게",
        romanization: "eonje / wae / eotteoke",
        meaning: "when / why / how",
        example: "어떻게 처리하면 될까요?",
        exampleTranslation: "How should I handle this?",
      },
      {
        hangul: "몇 / 어느 / 무슨 / 어떤",
        romanization: "myeot / eoneu / museun / eotteon",
        meaning: "how many / which / what kind of / what kind of or which",
        example: "몇 시예요? / 어느 팀이에요? / 무슨 일이에요?",
        exampleTranslation: "What time is it? / Which team is it? / What's going on?",
      },
      {
        hangul: "이 / 그 / 저",
        romanization: "i / geu / jeo",
        meaning: "this (near me) / that (near you or already known) / that over there",
        example: "이 방법 · 그 문제 · 저 건물",
        exampleTranslation: "this method · that problem · that building over there",
      },
      {
        hangul: "이것 / 그것 / 저것",
        romanization: "igeot / geugeot / jeogeot",
        meaning: "this thing / that thing / that thing over there",
        example: "이것도 확인해 주세요.",
        exampleTranslation: "Please check this too.",
        note: "In speech, 이것/그것/저것 are often shortened to 이거/그거/저거.",
      },
      {
        hangul: "여기 / 거기 / 저기",
        romanization: "yeogi / geogi / jeogi",
        meaning: "here / there / over there",
        example: "회의실이 어디예요? — 저기예요.",
        exampleTranslation: "Where is the meeting room? — It's over there.",
      },
    ],
    exercises: [
      {
        id: "grammar-20-e1",
        type: "multiple-choice",
        prompt: "Which word means 'how'?",
        options: ["왜", "언제", "어떻게", "누구"],
        answerIndex: 2,
        explanation: "어떻게 means 'how'.",
      },
      {
        id: "grammar-20-e2",
        type: "multiple-choice",
        prompt: "You point to a task on your own screen and say 'this task'. Which is best?",
        options: ["그 작업", "이 작업", "저 작업", "무슨 작업"],
        answerIndex: 1,
        explanation: "이 marks something near the speaker → 이 작업.",
      },
      {
        id: "grammar-20-e3",
        type: "type-answer",
        prompt: "Complete: 회의가 ___ 시작해요? (When does the meeting start?)",
        answer: "언제",
        explanation: "언제 asks when something happens.",
      },
    ],
  },
  {
    id: "grammar-21",
    track: "grammar",
    order: 21,
    title: "Numbers & Counters",
    subtitle: "Count people, things, time, floors, books, and more",
    level: "Beginner",
    estimatedMinutes: 13,
    completed: false,
    progress: 0,
    intro:
      "Korean uses two number systems. Native Korean numbers are common with counters such as people, things, age, and hours. Sino-Korean numbers are common for dates, minutes, money, floors, phone numbers, and larger numbers. The first four native numbers change before many counters: 하나→한, 둘→두, 셋→세, 넷→네.",
    cards: [
      {
        hangul: "하나 · 둘 · 셋 · 넷 · 다섯",
        romanization: "hana · dul · set · net · daseot",
        meaning: "Native Korean 1–5.",
        example: "한 명 · 두 개 · 세 시 · 네 살",
        exampleTranslation: "one person · two things · three o'clock · four years old",
        note: "Before many counters: 하나→한, 둘→두, 셋→세, 넷→네.",
      },
      {
        hangul: "일 · 이 · 삼 · 사 · 오",
        romanization: "il · i · sam · sa · o",
        meaning: "Sino-Korean 1–5.",
        example: "3층 · 10분 · 15,000원",
        exampleTranslation: "3rd floor · 10 minutes · 15,000 won",
      },
      {
        hangul: "십 · 백 · 천 · 만",
        romanization: "sip · baek · cheon · man",
        meaning: "ten · hundred · thousand · ten thousand",
        example: "삼만 오천 원",
        exampleTranslation: "35,000 won",
      },
      {
        hangul: "명 / 분",
        romanization: "myeong / bun",
        meaning: "Counters for people; 분 is the respectful person counter.",
        example: "세 명이 참석합니다. / 두 분 오십니다.",
        exampleTranslation: "Three people will attend. / Two people (honorific) are coming.",
      },
      {
        hangul: "개 / 번 / 대 / 권 / 장",
        romanization: "gae / beon / dae / gwon / jang",
        meaning: "things / times or number / machines-vehicles / books / flat items-pages",
        example: "파일 두 개 · 세 번 · 컴퓨터 한 대 · 책 두 권 · 종이 한 장",
        exampleTranslation: "two files · three times · one computer · two books · one sheet of paper",
      },
      {
        hangul: "시 / 분 / 살 / 층",
        romanization: "si / bun / sal / cheung",
        meaning: "hour / minute / age / floor",
        example: "오후 세 시 십 분 · 스물네 살 · 5층",
        exampleTranslation: "3:10 p.m. · 24 years old · 5th floor",
        note: "시 usually uses native Korean numbers; minutes and floors use Sino-Korean numbers.",
      },
      {
        hangul: "잔 / 병",
        romanization: "jan / byeong",
        meaning: "cups/glasses / bottles",
        example: "커피 한 잔 주세요. / 물 두 병 주세요.",
        exampleTranslation: "One coffee, please. / Two bottles of water, please.",
      },
    ],
    exercises: [
      {
        id: "grammar-21-e1",
        type: "multiple-choice",
        prompt: "How do you say 'three people' with 명?",
        options: ["셋 명", "세 명", "삼 명", "세 분명"],
        answerIndex: 1,
        explanation: "셋 changes to 세 before many counters → 세 명.",
      },
      {
        id: "grammar-21-e2",
        type: "multiple-choice",
        prompt: "Which system is normally used for minutes in 3:10?",
        options: ["Native Korean", "Sino-Korean", "Either with no difference", "English numbers only"],
        answerIndex: 1,
        explanation: "Hours use native Korean numbers, while minutes use Sino-Korean numbers.",
      },
      {
        id: "grammar-21-e3",
        type: "type-answer",
        prompt: "Complete: 컴퓨터 한 ___ (one computer).",
        answer: "대",
        explanation: "대 counts machines and vehicles, including computers.",
      },
    ],
  },
  {
    id: "grammar-22",
    track: "grammar",
    order: 22,
    title: "Time, Dates & Scheduling",
    subtitle: "Say when, from when, until when, and by when",
    level: "Beginner",
    estimatedMinutes: 12,
    completed: false,
    progress: 0,
    intro:
      "Daily life and office Korean constantly use dates, times, deadlines, and ranges. Dates use Sino-Korean numbers; clock hours normally use native Korean numbers; minutes use Sino-Korean numbers. 에 marks a time, 부터 marks a starting point, and 까지 marks an end point or deadline.",
    cards: [
      {
        hangul: "년 / 월 / 일",
        romanization: "nyeon / wol / il",
        meaning: "year / month / day — use Sino-Korean numbers.",
        example: "2026년 9월 3일",
        exampleTranslation: "September 3, 2026",
      },
      {
        hangul: "월요일 · 화요일 · 수요일 · 목요일 · 금요일",
        romanization: "woryoil · hwayoil · suyoil · mogyoil · geumyoil",
        meaning: "Monday · Tuesday · Wednesday · Thursday · Friday",
        example: "금요일에 회의가 있어요.",
        exampleTranslation: "There is a meeting on Friday.",
      },
      {
        hangul: "오전 / 오후 + 시 + 분",
        romanization: "ojeon / ohu + si + bun",
        meaning: "a.m. / p.m. + hour + minute",
        example: "오후 세 시 삼십 분에 시작합니다.",
        exampleTranslation: "It starts at 3:30 p.m.",
      },
      {
        hangul: "오늘 / 어제 / 내일",
        romanization: "oneul / eoje / naeil",
        meaning: "today / yesterday / tomorrow",
        example: "내일까지 완료하겠습니다.",
        exampleTranslation: "I will complete it by tomorrow.",
      },
      {
        hangul: "이번 주 / 다음 주 / 지난주",
        romanization: "ibeon ju / daeum ju / jinanju",
        meaning: "this week / next week / last week",
        example: "다음 주까지 진행해 주세요.",
        exampleTranslation: "Please proceed with it by next week.",
        note: "Write 이번 주 and 다음 주 with a space.",
      },
      {
        hangul: "부터 / 까지",
        romanization: "buteo / kkaji",
        meaning: "from / until, to, by",
        example: "오전 9시부터 오후 6시까지 일해요.",
        exampleTranslation: "I work from 9 a.m. to 6 p.m.",
      },
      {
        hangul: "시간 + 에",
        romanization: "sigan + e",
        meaning: "에 marks when an event happens.",
        example: "세 시에 만나요.",
        exampleTranslation: "Let's meet at three.",
        note: "Relative time words such as 오늘, 내일, 어제 often do not need 에.",
      },
    ],
    exercises: [
      {
        id: "grammar-22-e1",
        type: "multiple-choice",
        prompt: "Which is the natural way to say 'at 3 p.m.'?",
        options: ["오후 삼 시에", "오후 세 시에", "오후 셋 시에", "오후 삼 분에"],
        answerIndex: 1,
        explanation: "Clock hours use native Korean numbers: 세 시.",
      },
      {
        id: "grammar-22-e2",
        type: "multiple-choice",
        prompt: "Complete: 오전 9시___ 오후 6시까지 일해요. (I work from 9 to 6.)",
        options: ["에서", "부터", "에게", "보다"],
        answerIndex: 1,
        explanation: "부터 marks the starting point of a time range.",
      },
      {
        id: "grammar-22-e3",
        type: "type-answer",
        prompt: "Complete: 금요일___ 회의가 있어요. (There is a meeting on Friday.)",
        answer: "에",
        explanation: "에 marks the time when an event happens → 금요일에.",
      },
    ],
  },
  {
    id: "grammar-23",
    track: "grammar",
    order: 23,
    title: "Honorifics & Speech Levels",
    subtitle: "Sound respectful without making every sentence complicated",
    level: "Elementary",
    estimatedMinutes: 13,
    completed: false,
    progress: 0,
    intro:
      "Workplace Korean is not just grammar; it also marks respect. Use the polite -요 style for normal conversation, the formal -습니다/-ㅂ니다 style for reports and more formal settings, and -(으)시- when respectfully describing the subject's action or state. A few common verbs also have special honorific or humble forms.",
    cards: [
      {
        hangul: "-아요/어요 vs -습니다/-ㅂ니다",
        romanization: "-ayo/eoyo vs -seumnida/-mnida",
        meaning:
          "Both are polite. -요 is everyday polite conversation; -습니다/-ㅂ니다 is more formal and common in reports, announcements, and formal workplace speech.",
        example: "확인했어요. / 확인했습니다.",
        exampleTranslation: "I checked it. / I checked it (formal).",
      },
      {
        hangul: "-(으)시-",
        romanization: "-(eu)si-",
        meaning: "Subject honorific marker used when the subject deserves respect.",
        example: "팀장님이 지금 회의하고 계세요.",
        exampleTranslation: "The team leader is in a meeting now.",
      },
      {
        hangul: "있다 → 계시다 / 먹다 → 드시다",
        romanization: "itda → gyesida / meokda → deusida",
        meaning: "Common honorific replacements for exist/be and eat.",
        example: "차장님 지금 자리에 계세요?",
        exampleTranslation: "Is the deputy manager at their desk now?",
      },
      {
        hangul: "말하다 → 말씀하시다",
        romanization: "malhada → malsseumhasida",
        meaning: "Honorific way to say that a respected person speaks/says something.",
        example: "팀장님께서 그렇게 말씀하셨어요.",
        exampleTranslation: "The team leader said that.",
      },
      {
        hangul: "주다 → 드리다",
        romanization: "juda → deurida",
        meaning: "Humble 'give' used when you give/provide something to someone respected.",
        example: "확인 후 다시 공유드리겠습니다.",
        exampleTranslation: "I will share it again after checking.",
      },
      {
        hangul: "묻다 → 여쭙다 / 보다·만나다 → 뵙다",
        romanization: "mutda → yeojjupda / boda·mannada → boepda",
        meaning: "Humble forms for asking and seeing/meeting someone respected.",
        example: "한 가지 여쭤봐도 될까요? / 내일 뵙겠습니다.",
        exampleTranslation: "May I ask one thing? / See you tomorrow (respectful).",
      },
      {
        hangul: "님 / 께서 / 께",
        romanization: "nim / kkeseo / kke",
        meaning: "Respectful title suffix / honorific subject particle / honorific 'to'.",
        example: "팀장님께서 말씀하셨어요. / 팀장님께 메일을 드렸어요.",
        exampleTranslation: "The team leader said it. / I sent an email to the team leader.",
      },
    ],
    exercises: [
      {
        id: "grammar-23-e1",
        type: "multiple-choice",
        prompt: "Which is the humble workplace verb meaning 'to ask'?",
        options: ["말씀하시다", "드시다", "여쭙다", "계시다"],
        answerIndex: 2,
        explanation: "여쭙다 is a humble form of 묻다/물어보다 when asking someone respectfully.",
      },
      {
        id: "grammar-23-e2",
        type: "multiple-choice",
        prompt: "Which sentence is the more formal status-report style?",
        options: ["확인했어요.", "확인했습니다.", "확인해.", "확인했어."],
        answerIndex: 1,
        explanation: "-습니다/-ㅂ니다 is the formal polite style often used in workplace reporting.",
      },
      {
        id: "grammar-23-e3",
        type: "type-answer",
        prompt: "Complete the respectful phrase: 한 가지 ___봐도 될까요? (May I ask one thing?)",
        answer: "여쭤",
        explanation: "여쭤보다/여쭙다 is the humble form used for respectfully asking.",
      },
    ],
  },
  {
    id: "grammar-24",
    track: "grammar",
    order: 24,
    title: "Workplace Politeness Patterns",
    subtitle: "Ask, report, soften, and update naturally at work",
    level: "Elementary",
    estimatedMinutes: 14,
    completed: false,
    progress: 0,
    intro:
      "Workplace Korean often sounds natural because speakers soften requests, avoid overconfident claims, and clearly state what they will do next. Learn these as reusable sentence frames, not as isolated endings. They match common Hengo workplace vocabulary such as 확인하다, 처리하다, 공유하다, 일정, 완료, and 담당.",
    cards: [
      {
        hangul: "-아/어 주실 수 있을까요?",
        romanization: "-a/eo jusil su isseulkkayo?",
        meaning: "Could you please do ...? A respectful, useful request pattern.",
        example: "이 부분을 다시 설명해 주실 수 있을까요?",
        exampleTranslation: "Could you explain this part again?",
      },
      {
        hangul: "-(으)면 될까요?",
        romanization: "-(eu)myeon doelkkayo?",
        meaning: "What should I do / would it be okay if I do ...? Useful when confirming a process.",
        example: "이건 어떻게 처리하면 될까요?",
        exampleTranslation: "How should I handle this?",
      },
      {
        hangul: "-(으)ㄹ 것 같습니다",
        romanization: "-(eu)l geot gatseumnida",
        meaning: "I think it will / it seems it will. A formal way to soften a prediction or concern.",
        example: "일정이 조금 늦어질 것 같습니다.",
        exampleTranslation: "I think the schedule may be slightly delayed.",
      },
      {
        hangul: "-겠습니다 / -드리겠습니다",
        romanization: "-getseumnida / -deurigetseumnida",
        meaning: "Formal intention/commitment; 드리겠습니다 adds a humble 'for you' nuance when suitable.",
        example: "확인하고 다시 말씀드리겠습니다.",
        exampleTranslation: "I will check and get back to you.",
      },
      {
        hangul: "-(으)ㄹ 예정입니다",
        romanization: "-(eu)l yejeongimnida",
        meaning: "It is planned/scheduled to ...; useful for realistic schedule updates.",
        example: "내일까지 완료할 예정입니다.",
        exampleTranslation: "It is planned to be completed by tomorrow / I plan to complete it by tomorrow.",
      },
      {
        hangul: "-(으)ㄴ/는데요",
        romanization: "-(eu)n/neundeyo",
        meaning:
          "Gives background and softens what follows. Very common when explaining a situation before a request or update.",
        example: "지금 확인 중인데요. 잠시만 기다려 주세요.",
        exampleTranslation: "I'm checking it now. Please wait a moment.",
      },
      {
        hangul: "확인 부탁드립니다",
        romanization: "hwagin butakdeurimnida",
        meaning: "Please check/review it. A concise formal workplace request.",
        example: "수정했습니다. 다시 확인 부탁드립니다.",
        exampleTranslation: "I've fixed it. Please check it again.",
        note: "Useful in chat/email, but a full sentence such as 확인해 주실 수 있을까요? can sound warmer in conversation.",
      },
    ],
    exercises: [
      {
        id: "grammar-24-e1",
        type: "multiple-choice",
        prompt: "You are unsure how to handle a task. Which sentence is the most useful confirmation pattern?",
        options: [
          "어떻게 처리하면 될까요?",
          "처리합니다.",
          "처리하지 마세요.",
          "처리했어요?",
        ],
        answerIndex: 0,
        explanation: "-(으)면 될까요? politely asks what action/process is appropriate.",
      },
      {
        id: "grammar-24-e2",
        type: "multiple-choice",
        prompt: "Which update politely softens an expected delay?",
        options: [
          "일정이 늦어요.",
          "일정이 조금 늦어질 것 같습니다.",
          "일정을 늦게 해요.",
          "일정이 늦지 마세요.",
        ],
        answerIndex: 1,
        explanation: "-(으)ㄹ 것 같습니다 is a natural formal softener for predictions/concerns.",
      },
      {
        id: "grammar-24-e3",
        type: "type-answer",
        prompt: "Complete: 수정했습니다. 다시 확인 ___드립니다. (I've fixed it. Please check again.)",
        answer: "부탁",
        explanation: "확인 부탁드립니다 is a common concise formal workplace request.",
      },
    ],
  },
]
