import type { PhraseCardContentInput } from "@/lib/korean-phrasebook/schemas"

export type StudyVocabLevel = "basic" | "intermediate" | "advanced"

export interface StudyVocabEntry {
  term: string
  meaning: string
  level: StudyVocabLevel
}

export const SOCIAL_AWARENESS_PACK = {
  sourceKey: "script-social-awareness-v1",
  titleKo: "사회성 · 직장 배려 표현",
  titleEn: "Social Awareness & Workplace Communication",
  description:
    "Script-based Korean study pack covering workplace roles, bonuses, phone etiquette, consideration, and common spoken grammar. Learn the core expressions first; advanced cards are mainly for recognition.",
  category: "script-social-awareness",
} as const

export const SOCIAL_AWARENESS_VOCAB: StudyVocabEntry[] = [
  // Basic — high-frequency words worth actively learning first.
  { term: "사람", meaning: "person", level: "basic" },
  { term: "회사", meaning: "company", level: "basic" },
  { term: "다니다", meaning: "to attend / go regularly; to work at", level: "basic" },
  { term: "여러 가지", meaning: "various kinds / several kinds", level: "basic" },
  { term: "있다", meaning: "to exist / to have", level: "basic" },
  { term: "없다", meaning: "to not exist / to not have", level: "basic" },
  { term: "받다", meaning: "to receive", level: "basic" },
  { term: "얼마", meaning: "how much", level: "basic" },
  { term: "얘기", meaning: "talk / conversation / story", level: "basic" },
  { term: "사실", meaning: "actually / in fact", level: "basic" },
  { term: "어디", meaning: "where", level: "basic" },
  { term: "누가", meaning: "who (subject form of 누구)", level: "basic" },
  { term: "듣다", meaning: "to hear / to listen", level: "basic" },
  { term: "생각하다", meaning: "to think", level: "basic" },
  { term: "많이", meaning: "a lot / much", level: "basic" },
  { term: "만나다", meaning: "to meet", level: "basic" },
  { term: "전화", meaning: "phone / phone call", level: "basic" },
  { term: "오다", meaning: "to come", level: "basic" },
  { term: "시간", meaning: "time / hour", level: "basic" },
  { term: "안", meaning: "not (short-form negation)", level: "basic" },
  { term: "문자", meaning: "text message / SMS", level: "basic" },
  { term: "보내다", meaning: "to send", level: "basic" },
  { term: "지금", meaning: "now", level: "basic" },
  { term: "어떤", meaning: "what kind of / which", level: "basic" },
  { term: "급하다", meaning: "to be urgent / to be in a hurry", level: "basic" },
  { term: "아니면", meaning: "or / otherwise", level: "basic" },
  { term: "다시", meaning: "again / back", level: "basic" },
  { term: "일", meaning: "work / matter / thing", level: "basic" },
  { term: "다음 날", meaning: "the next day", level: "basic" },
  { term: "때", meaning: "time / when", level: "basic" },
  { term: "조금", meaning: "a little", level: "basic" },
  { term: "너무", meaning: "too / very", level: "basic" },
  { term: "이렇게", meaning: "like this / in this way", level: "basic" },
  { term: "그러면", meaning: "then / in that case", level: "basic" },
  { term: "그럼", meaning: "then / well then", level: "basic" },
  { term: "좋다", meaning: "to be good", level: "basic" },
  { term: "이제", meaning: "now / from now on", level: "basic" },
  { term: "예를 들면", meaning: "for example", level: "basic" },

  // Intermediate — practical workplace and communication vocabulary.
  { term: "직군", meaning: "job category / occupational group", level: "intermediate" },
  { term: "직급", meaning: "job rank / position level", level: "intermediate" },
  { term: "정규직", meaning: "permanent / regular employee", level: "intermediate" },
  { term: "계약직", meaning: "contract employee", level: "intermediate" },
  { term: "파견직", meaning: "dispatched / agency employee", level: "intermediate" },
  { term: "외부 사원", meaning: "external staff member", level: "intermediate" },
  { term: "성과급", meaning: "performance bonus", level: "intermediate" },
  { term: "처리되다", meaning: "to be processed / handled", level: "intermediate" },
  { term: "누군가", meaning: "someone", level: "intermediate" },
  { term: "해당되다", meaning: "to apply / be applicable / be eligible", level: "intermediate" },
  { term: "사회성", meaning: "social skills / social awareness", level: "intermediate" },
  { term: "상대방", meaning: "the other person / counterpart", level: "intermediate" },
  { term: "배려하다", meaning: "to be considerate / take someone into consideration", level: "intermediate" },
  { term: "경영자", meaning: "business owner / executive / manager", level: "intermediate" },
  { term: "중소기업", meaning: "small or medium-sized enterprise (SME)", level: "intermediate" },
  { term: "컨설팅", meaning: "consulting", level: "intermediate" },
  { term: "부재중 전화", meaning: "missed call", level: "intermediate" },
  { term: "통", meaning: "counter for calls, messages, or letters", level: "intermediate" },
  { term: "해결되다", meaning: "to be resolved / solved", level: "intermediate" },
  { term: "상대", meaning: "the other person / counterpart", level: "intermediate" },
  { term: "사정", meaning: "circumstances / situation / reason", level: "intermediate" },
  { term: "여유", meaning: "spare time / room / flexibility", level: "intermediate" },
  { term: "경우", meaning: "case / situation", level: "intermediate" },
  { term: "기본적으로", meaning: "basically / fundamentally", level: "intermediate" },
  { term: "굉장히", meaning: "very / extremely", level: "intermediate" },
  { term: "서너", meaning: "three or four", level: "intermediate" },
  { term: "약간", meaning: "a little / somewhat / kind of", level: "intermediate" },
  { term: "딱", meaning: "exactly / just; spoken emphasis", level: "intermediate" },
  { term: "막", meaning: "spoken filler/intensifier: just, freely, or without much thought depending on context", level: "intermediate" },
  { term: "이런 식으로", meaning: "in this way / like this", level: "intermediate" },
  { term: "분", meaning: "person (honorific); respectful counter for people", level: "intermediate" },
  { term: "느끼다", meaning: "to feel", level: "intermediate" },
  { term: "이해되다", meaning: "to be understandable / make sense", level: "intermediate" },

  // Advanced / recognition — native spoken chunks from the script.
  { term: "이른바", meaning: "so-called / what is called", level: "advanced" },
  { term: "리턴콜", meaning: "callback / return call", level: "advanced" },
  { term: "한 장", meaning: "one sheet; colloquial money unit in some contexts (exact amount depends on context)", level: "advanced" },
  { term: "생각이 들다", meaning: "a thought occurs / to find oneself thinking", level: "advanced" },
  { term: "사회성이 없다", meaning: "to lack social awareness / social skills", level: "advanced" },
  { term: "사회성이 좋다", meaning: "to have good social awareness / social skills", level: "advanced" },
  { term: "상대를 배려하다", meaning: "to be considerate of the other person", level: "advanced" },
  { term: "사정이 있다", meaning: "to have circumstances / have a reason", level: "advanced" },
  { term: "여유가 있다", meaning: "to have time / room / flexibility", level: "advanced" },
  { term: "해당이 되다", meaning: "to apply / be eligible (expanded spoken form of 해당되다)", level: "advanced" },
  { term: "좀 아니다", meaning: "to be not quite right / not really good; a soft indirect expression", level: "advanced" },
  { term: "전화가 오다", meaning: "to get / receive a phone call", level: "advanced" },
  { term: "전화를 받다", meaning: "to answer a phone call", level: "advanced" },
  { term: "전화를 안 받다", meaning: "to not answer a phone call", level: "advanced" },
  { term: "부재중 전화가 오다", meaning: "to get a missed call", level: "advanced" },
  { term: "문자를 보내 놓다", meaning: "to send a text and leave it done / send it in advance", level: "advanced" },
  { term: "다시 전화하다", meaning: "to call back", level: "advanced" },
  { term: "이런 일로", meaning: "about this matter / for this reason", level: "advanced" },
  { term: "그럴 때가 있다", meaning: "there are times when that happens", level: "advanced" },
]

export const SOCIAL_AWARENESS_PHRASES: PhraseCardContentInput[] = [
  {
    category: "workplace",
    situation: "eligibility",
    difficulty: "easy",
    question: {
      korean: "저도 해당돼요?",
      romanization: "jeodo haedangdwaeyo?",
      english: "Does this apply to me too? / Am I eligible too?",
      register: "polite",
    },
    questionVariants: ["저도 해당되나요?"],
    answers: [
      {
        korean: "네, 해당돼요.",
        romanization: "ne, haedangdwaeyo.",
        english: "Yes, it applies to you.",
        register: "polite",
        isRecommended: true,
      },
      {
        korean: "아니요, 해당되지 않아요.",
        romanization: "aniyo, haedangdoeji anayo.",
        english: "No, it does not apply to you.",
        register: "polite",
        isRecommended: false,
      },
    ],
    usageNote: "Core workplace chunk: ~에 해당되다 = to apply / be eligible.",
    vocabulary: [
      { korean: "해당되다", english: "to apply / be eligible" },
      { korean: "저도", english: "me too / I too" },
    ],
    tags: ["script-study", "workplace", "eligibility"],
  },
  {
    category: "daily",
    situation: "missed-call",
    difficulty: "easy",
    question: {
      korean: "전화를 못 받았어요. 어떻게 해야 해요?",
      romanization: "jeonhwareul mot badasseoyo. eotteoke haeya haeyo?",
      english: "I couldn't answer the call. What should I do?",
      register: "polite",
    },
    questionVariants: ["전화를 못 받았는데 어떻게 해야 해요?"],
    answers: [
      {
        korean: "문자를 보내거나 다시 전화하면 돼요.",
        romanization: "munjareul bonaegeona dasi jeonhwahamyeon dwaeyo.",
        english: "You can send a text or call back.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Useful phone-etiquette response. 못 받았어요 means 'couldn't answer.'",
    vocabulary: [
      { korean: "문자", english: "text message" },
      { korean: "다시 전화하다", english: "to call back" },
    ],
    tags: ["script-study", "phone", "daily"],
  },
  {
    category: "daily",
    situation: "missed-call-count",
    difficulty: "easy",
    question: {
      korean: "부재중 전화가 몇 통 왔어요?",
      romanization: "bujaejung jeonhwaga myeot tong wasseoyo?",
      english: "How many missed calls did you get?",
      register: "polite",
    },
    questionVariants: ["부재중 전화가 몇 개 왔어요?"],
    answers: [
      {
        korean: "세 통 왔어요.",
        romanization: "se tong wasseoyo.",
        english: "I got three calls.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "통 is the normal counter for phone calls.",
    vocabulary: [
      { korean: "부재중 전화", english: "missed call" },
      { korean: "통", english: "counter for calls" },
    ],
    tags: ["script-study", "phone", "counter"],
  },
  {
    category: "workplace",
    situation: "phone-purpose",
    difficulty: "easy",
    question: {
      korean: "무슨 일로 전화하셨어요?",
      romanization: "museun illo jeonhwahasyeosseoyo?",
      english: "What did you call about?",
      register: "polite",
    },
    questionVariants: ["어떤 일로 전화하셨어요?"],
    answers: [
      {
        korean: "이 일 때문에 전화드렸습니다.",
        romanization: "i il ttaemune jeonhwadeuryeotsseumnida.",
        english: "I called because of this matter.",
        register: "formal",
        isRecommended: true,
      },
    ],
    usageNote: "전화드리다 is the respectful form of 전화하다 when speaking to a senior/client.",
    vocabulary: [
      { korean: "무슨 일", english: "what matter / what happened" },
      { korean: "전화드리다", english: "to call (respectfully)" },
    ],
    tags: ["script-study", "workplace", "phone"],
  },
  {
    category: "workplace",
    situation: "urgency",
    difficulty: "easy",
    question: {
      korean: "급한 일이에요?",
      romanization: "geupan irieyo?",
      english: "Is it urgent?",
      register: "polite",
    },
    questionVariants: ["많이 급한가요?"],
    answers: [
      {
        korean: "아니요, 급하지 않아요.",
        romanization: "aniyo, geuphaji anayo.",
        english: "No, it isn't urgent.",
        register: "polite",
        isRecommended: true,
      },
      {
        korean: "네, 조금 급합니다.",
        romanization: "ne, jogeum geupamnida.",
        english: "Yes, it is a little urgent.",
        register: "formal",
        isRecommended: false,
      },
    ],
    usageNote: "급하다 is common in work messages when clarifying urgency.",
    vocabulary: [{ korean: "급하다", english: "to be urgent" }],
    tags: ["script-study", "workplace", "urgency"],
  },
  {
    category: "workplace",
    situation: "resolution",
    difficulty: "easy",
    question: {
      korean: "문제가 해결됐어요?",
      romanization: "munjega haegyeoldwaesseoyo?",
      english: "Has the problem been resolved?",
      register: "polite",
    },
    questionVariants: ["이제 해결됐어요?"],
    answers: [
      {
        korean: "네, 해결됐습니다.",
        romanization: "ne, haegyeoldwaetsseumnida.",
        english: "Yes, it has been resolved.",
        register: "formal",
        isRecommended: true,
      },
    ],
    usageNote: "Very useful status-update pair for workplace Korean.",
    vocabulary: [
      { korean: "문제", english: "problem" },
      { korean: "해결되다", english: "to be resolved" },
    ],
    tags: ["script-study", "workplace", "status-update"],
  },
  {
    category: "workplace",
    situation: "callback",
    difficulty: "easy",
    question: {
      korean: "제가 다시 전화드릴까요?",
      romanization: "jega dasi jeonhwadeurilkkayo?",
      english: "Shall I call you back?",
      register: "polite",
    },
    questionVariants: ["제가 나중에 다시 전화드릴까요?"],
    answers: [
      {
        korean: "네, 부탁드립니다.",
        romanization: "ne, butakdeurimnida.",
        english: "Yes, please.",
        register: "formal",
        isRecommended: true,
      },
      {
        korean: "아니요, 시간 있을 때 연락 주세요.",
        romanization: "aniyo, sigan isseul ttae yeollak juseyo.",
        english: "No, please contact me when you have time.",
        register: "polite",
        isRecommended: false,
      },
    ],
    usageNote: "Prefer 다시 전화드리다 over the loanword 리턴콜 in polite workplace speech.",
    vocabulary: [
      { korean: "다시", english: "again / back" },
      { korean: "리턴콜", english: "callback (loanword)" },
    ],
    tags: ["script-study", "workplace", "phone"],
  },
  {
    category: "workplace",
    situation: "flexible-time",
    difficulty: "easy",
    question: {
      korean: "언제 확인하면 될까요?",
      romanization: "eonje hwaginhamyeon doelkkayo?",
      english: "When should I check it?",
      register: "polite",
    },
    questionVariants: ["언제 확인할까요?"],
    answers: [
      {
        korean: "시간 있을 때 확인해 주세요.",
        romanization: "sigan isseul ttae hwaginhae juseyo.",
        english: "Please check it when you have time.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Core chunk: N/V-(으)ㄹ 때 = when / at the time that...",
    vocabulary: [
      { korean: "여유", english: "spare time / room" },
      { korean: "확인하다", english: "to check / confirm" },
    ],
    tags: ["script-study", "workplace", "time"],
  },
  {
    category: "daily",
    situation: "consideration",
    difficulty: "easy",
    question: {
      korean: "상대방을 왜 배려해야 해요?",
      romanization: "sangdaebangeul wae baeryeohaeya haeyo?",
      english: "Why should we be considerate of the other person?",
      register: "polite",
    },
    questionVariants: ["왜 상대방을 생각해야 해요?"],
    answers: [
      {
        korean: "상대방의 상황을 생각하는 게 중요해요.",
        romanization: "sangdaebangui sanghwangeul saenggakhaneun ge jungyohaeyo.",
        english: "It is important to think about the other person's situation.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "배려하다 is one of the key words in this script.",
    vocabulary: [
      { korean: "상대방", english: "the other person" },
      { korean: "배려하다", english: "to be considerate" },
    ],
    tags: ["script-study", "social-awareness", "consideration"],
  },
  {
    category: "daily",
    situation: "assumption",
    difficulty: "medium",
    question: {
      korean: "상대방이 전화를 안 받으면 어떻게 생각해요?",
      romanization: "sangdaebangi jeonhwareul an badeumyeon eotteoke saenggakaeyo?",
      english: "What do you think when the other person does not answer the phone?",
      register: "polite",
    },
    questionVariants: ["상대방이 전화를 안 받으면요?"],
    answers: [
      {
        korean: "사정이 있겠지 하고 생각해요.",
        romanization: "sajeongi itgetji hago saenggakaeyo.",
        english: "I think, 'They probably have a reason.'",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition chunk: -겠지 = probably / I suppose.",
    vocabulary: [
      { korean: "사정", english: "circumstances / reason" },
      { korean: "-겠지", english: "probably / I suppose" },
    ],
    tags: ["script-study", "spoken-korean", "assumption"],
  },
  {
    category: "daily",
    situation: "frequency",
    difficulty: "easy",
    question: {
      korean: "이런 일이 자주 있어요?",
      romanization: "ireon iri jaju isseoyo?",
      english: "Does this kind of thing happen often?",
      register: "polite",
    },
    questionVariants: ["이런 경우가 자주 있어요?"],
    answers: [
      {
        korean: "가끔 그럴 때가 있어요.",
        romanization: "gakkeum geureol ttaega isseoyo.",
        english: "Sometimes that happens.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Common chunk: -ㄹ 때가 있어요 = there are times when...",
    vocabulary: [
      { korean: "경우", english: "case / situation" },
      { korean: "그럴 때가 있다", english: "there are times when that happens" },
    ],
    tags: ["script-study", "spoken-korean", "frequency"],
  },
  {
    category: "daily",
    situation: "reaction",
    difficulty: "medium",
    question: {
      korean: "이 상황을 어떻게 느꼈어요?",
      romanization: "i sanghwangeul eotteoke neukkyeosseoyo?",
      english: "How did you feel about this situation?",
      register: "polite",
    },
    questionVariants: ["이 상황에 대해 어떻게 생각했어요?"],
    answers: [
      {
        korean: "상대를 배려하지 않는다고 느꼈어요.",
        romanization: "sangdaereul baeryeohaji anneundago neukkyeosseoyo.",
        english: "I felt that they were not being considerate of the other person.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Useful opinion pattern: -다고 느끼다 = to feel that...",
    vocabulary: [
      { korean: "느끼다", english: "to feel" },
      { korean: "상대", english: "the other person" },
    ],
    tags: ["script-study", "social-awareness", "opinion"],
  },
  {
    category: "workplace",
    situation: "work-experience",
    difficulty: "medium",
    question: {
      korean: "회사에 다니다 보면 어떤 사람들을 만나요?",
      romanization: "hoesae danida bomyeon eotteon saramdeureul mannayo?",
      english: "As you work at a company, what kinds of people do you meet?",
      register: "polite",
    },
    questionVariants: ["회사 생활을 하다 보면 어떤 사람들을 만나요?"],
    answers: [
      {
        korean: "여러 가지 직군의 사람들을 만나요.",
        romanization: "yeoreo gaji jikgunui saramdeureul mannayo.",
        english: "I meet people from various job groups.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition pattern: V-다 보면 = as you keep doing / when you do something over time.",
    vocabulary: [
      { korean: "직군", english: "job category" },
      { korean: "-다 보면", english: "as you keep doing / over time" },
    ],
    tags: ["script-study", "workplace", "grammar-recognition"],
  },
  {
    category: "workplace",
    situation: "employment-types",
    difficulty: "medium",
    question: {
      korean: "직급 말고 어떤 고용 형태가 있어요?",
      romanization: "jikgeup malgo eotteon goyong hyeongtaega isseoyo?",
      english: "Besides job rank, what employment types are there?",
      register: "polite",
    },
    questionVariants: ["정규직 말고 어떤 고용 형태가 있어요?"],
    answers: [
      {
        korean: "정규직, 계약직, 파견직 등이 있어요.",
        romanization: "jeonggyujik, gyeyakjik, pagyeonjik deungi isseoyo.",
        english: "There are permanent, contract, and dispatched employees, among others.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Common pattern: A 말고 B = not A / besides A, but B.",
    vocabulary: [
      { korean: "직급", english: "job rank" },
      { korean: "정규직", english: "permanent employee" },
      { korean: "계약직", english: "contract employee" },
      { korean: "파견직", english: "dispatched employee" },
    ],
    tags: ["script-study", "workplace", "employment"],
  },
  {
    category: "workplace",
    situation: "message-first",
    difficulty: "medium",
    question: {
      korean: "왜 문자를 보내 놓아요?",
      romanization: "wae munjareul bonae noayo?",
      english: "Why do you send a text and leave it there?",
      register: "polite",
    },
    questionVariants: ["왜 먼저 문자를 보내요?"],
    answers: [
      {
        korean: "상대방이 나중에 확인할 수 있어요.",
        romanization: "sangdaebangi najunge hwaginhal su isseoyo.",
        english: "The other person can check it later.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition pattern: V-아/어 놓다 = do something and leave it done / do it in advance.",
    vocabulary: [
      { korean: "문자를 보내 놓다", english: "to send a text and leave it done" },
      { korean: "-아/어 놓다", english: "do and leave it done / do in advance" },
    ],
    tags: ["script-study", "phone", "grammar-recognition"],
  },
  {
    category: "workplace",
    situation: "reason-explanation",
    difficulty: "medium",
    question: {
      korean: "왜 지금 답하지 않아도 돼요?",
      romanization: "wae jigeum daphaji anado dwaeyo?",
      english: "Why is it okay not to answer right now?",
      register: "polite",
    },
    questionVariants: ["왜 바로 답하지 않아도 돼요?"],
    answers: [
      {
        korean: "급하지 않게 여유 있을 때 할 수 있거든요.",
        romanization: "geuphaji anke yeoyu isseul ttae hal su itgeodeunyo.",
        english: "Because they can do it later when they have time, without rushing.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition pattern: -거든요 often gives background or a reason in conversation.",
    vocabulary: [
      { korean: "여유", english: "spare time / room" },
      { korean: "-거든요", english: "you see / because (spoken explanation)" },
    ],
    tags: ["script-study", "spoken-korean", "grammar-recognition"],
  },
  {
    category: "daily",
    situation: "experienced-impression",
    difficulty: "hard",
    question: {
      korean: "그 사람을 보고 어떤 생각이 들었어요?",
      romanization: "geu sarameul bogo eotteon saenggagi deureosseoyo?",
      english: "What did you think when you saw that person?",
      register: "polite",
    },
    questionVariants: ["그 상황을 보고 어떤 생각이 들었어요?"],
    answers: [
      {
        korean: "상대를 배려하지 않는다는 생각이 들더라고요.",
        romanization: "sangdaereul baeryeohaji anneundaneun saenggagi deuldeoragoyo.",
        english: "I found myself thinking that they were not considerate of others.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition only for now: -더라고요 reports something the speaker personally noticed or experienced.",
    vocabulary: [
      { korean: "생각이 들다", english: "a thought occurs / to find oneself thinking" },
      { korean: "-더라고요", english: "I noticed / found from experience" },
    ],
    tags: ["script-study", "spoken-korean", "advanced-recognition"],
  },
  {
    category: "workplace",
    situation: "bonus-consideration",
    difficulty: "medium",
    question: {
      korean: "왜 성과급 얘기를 조심해야 해요?",
      romanization: "wae seonggwageup yaegireul josimhaeya haeyo?",
      english: "Why should you be careful when talking about performance bonuses?",
      register: "polite",
    },
    questionVariants: ["성과급 이야기를 왜 조심해야 해요?"],
    answers: [
      {
        korean: "성과급에 해당되지 않는 사람도 있을 거잖아요.",
        romanization: "seonggwageube haedangdoeji anneun saramdo isseul geojanayo.",
        english: "There may be people who are not eligible for the bonus, you know.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition pattern: -거잖아요 = you know / as you know / right? It assumes shared context.",
    vocabulary: [
      { korean: "성과급", english: "performance bonus" },
      { korean: "-거잖아요", english: "you know / as you know / right?" },
    ],
    tags: ["script-study", "workplace", "social-awareness"],
  },
  {
    category: "daily",
    situation: "regardless",
    difficulty: "hard",
    question: {
      korean: "주변에 누가 있으면 어떻게 해야 해요?",
      romanization: "jubyeone nuga isseumyeon eotteoke haeya haeyo?",
      english: "What should you do when other people are around?",
      register: "polite",
    },
    questionVariants: ["주변에 사람이 있으면 어떻게 말해야 해요?"],
    answers: [
      {
        korean: "주변에 사람이 있든 말든 상대를 배려해야 해요.",
        romanization: "jubyeone sarami itdeun maldeun sangdaereul baeryeohaeya haeyo.",
        english: "Whether people are around or not, you should be considerate of others.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition only for now: V-든 말든 = whether ... or not / regardless of whether...",
    vocabulary: [
      { korean: "-든 말든", english: "whether ... or not" },
      { korean: "상대를 배려하다", english: "to be considerate of the other person" },
    ],
    tags: ["script-study", "spoken-korean", "advanced-recognition"],
  },
  {
    category: "workplace",
    situation: "spoken-sequence",
    difficulty: "hard",
    question: {
      korean: "왜 그 사람이 문제라고 생각했어요?",
      romanization: "wae geu sarami munjerago saenggakaesseoyo?",
      english: "Why did you think that person's behavior was a problem?",
      register: "polite",
    },
    questionVariants: ["그 사람의 어떤 점이 문제였어요?"],
    answers: [
      {
        korean: "성과급을 받아 가지고 주변 사람을 생각하지 않았어요.",
        romanization: "seonggwageubeul bada gajigo jubyeon sarameul saenggakhaji anasseoyo.",
        english: "They got the bonus and did not think about the people around them.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition only for now: V-아/어 가지고 is a common spoken connector meaning 'and then' or 'because.'",
    vocabulary: [
      { korean: "-아/어 가지고", english: "and then / because (spoken)" },
      { korean: "주변", english: "surroundings / people around" },
    ],
    tags: ["script-study", "spoken-korean", "advanced-recognition"],
  },
  {
    category: "workplace",
    situation: "contrast",
    difficulty: "hard",
    question: {
      korean: "중소기업의 경영자를 만나도 사람마다 달라요?",
      romanization: "jungsogieobui gyeongyeongjareul mannado sarammada dallayo?",
      english: "Even among SME business owners, are people different?",
      register: "polite",
    },
    questionVariants: ["경영자들도 사람마다 달라요?"],
    answers: [
      {
        korean: "네, 중소기업의 경영자를 만난다 하더라도 사람마다 달라요.",
        romanization: "ne, jungsogieobui gyeongyeongjareul mannanda hadeorado sarammada dallayo.",
        english: "Yes. Even if you meet SME business owners, each person is different.",
        register: "polite",
        isRecommended: true,
      },
    ],
    usageNote: "Recognition only for now: V-다 하더라도 = even if / even though.",
    vocabulary: [
      { korean: "경영자", english: "business owner / executive" },
      { korean: "중소기업", english: "small or medium-sized enterprise" },
      { korean: "-다 하더라도", english: "even if / even though" },
    ],
    tags: ["script-study", "workplace", "advanced-recognition"],
  },
]

export const SOCIAL_AWARENESS_VOCAB_COUNTS = SOCIAL_AWARENESS_VOCAB.reduce(
  (counts, entry) => {
    counts[entry.level] += 1
    return counts
  },
  { basic: 0, intermediate: 0, advanced: 0 } as Record<StudyVocabLevel, number>,
)
